# Generated by Django 5.2.17 on 2026-09-19 03:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'mecánico',
                'verbose_name_plural': 'mecánicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('kilometraje_ingreso', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('motivo_ingreso', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('DETENIDO_REPUESTOS', 'Detenido por repuestos'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='service_orders.mechanic')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'orden de servicio',
                'verbose_name_plural': 'órdenes de servicio',
                'ordering': ['-fecha_ingreso', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('DETENIDO_REPUESTOS', 'Detenido por repuestos'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], max_length=25)),
                ('estado_nuevo', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('DETENIDO_REPUESTOS', 'Detenido por repuestos'), ('TERMINADO', 'Terminado'), ('ENTREGADO', 'Entregado')], max_length=25)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='service_orders.serviceorder')),
            ],
            options={
                'verbose_name': 'historial de estado',
                'verbose_name_plural': 'historial de estados',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ServicePerformed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('es_preventivo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_performed', to='service_orders.serviceorder')),
            ],
            options={
                'verbose_name': 'servicio realizado',
                'verbose_name_plural': 'servicios realizados',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='serviceorder',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ENTREGADO'), _negated=True), fields=('vehicle',), name='unique_open_order_per_vehicle'),
        ),
    ]
