# Generated by Django 5.2.17 on 2026-09-19 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONTACTADO', 'Contactado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12)),
                ('mensaje', models.TextField(blank=True)),
                ('contactado_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='maintenance.maintenanceschedule')),
            ],
            options={
                'verbose_name': 'recordatorio',
                'verbose_name_plural': 'recordatorios',
                'ordering': ['fecha_programada', 'created_at'],
            },
        ),
    ]
