# Generated by Django 5.2.17 on 2026-09-19 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('intervalo_km', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('intervalo_dias', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('ultimo_kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('ultima_fecha', models.DateField(blank=True, null=True)),
                ('proximo_kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('proxima_fecha', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_schedules', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'plan de mantenimiento',
                'verbose_name_plural': 'planes de mantenimiento',
                'ordering': ['vehicle', 'nombre_servicio'],
            },
        ),
    ]
