# Generated by Django 5.2.17 on 2026-09-19 02:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('anio', models.PositiveIntegerField(validators=[vehicles.models.validate_vehicle_year])),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('kilometraje_actual', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ingreso', models.DateField(default=django.utils.timezone.localdate)),
                ('estado', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('perfil_uso', models.CharField(choices=[('BAJO', 'Bajo'), ('NORMAL', 'Normal'), ('ALTO', 'Alto')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='owners.owner')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['placa'],
            },
        ),
    ]
